### ISSUE TITLE
Timeline crash

### ISSUE THREAD

**Issue by skyfaller** [PicoJr/rtw#28]
Yesterday my rtw activities got into a state where `rtw day` errors out like so:
```
nelson@Valence ~/D/G/devops (master) [1]> rtw day
thread 'main' panicked at 'assertion failed: chunk_size != 0', /private/tmp/rust-20200608-12669-3dsoul/rustc-1.44.0-src/src/libcore/macros/mod.rs:34:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Now that it's not the same day today, `rtw week` has that error.

Unfortunately, I can't figure out how to run with `RUST_BACKTRACE=1`, perhaps because I'm using Fish shell... the environment variable seems to be set, but the error remains the same, sorry I'm a noob.
```
nelson@Valence ~> echo $RUST_BACKTRACE
1
```
I'm attaching my activities file, hopefully that helps. Please don't mock my lazy Monday, which seems to mostly consist of endless quarantine dishes ;-)
[rtwh.json.tar.gz](https://github.com/PicoJr/rtw/files/4786602/rtwh.json.tar.gz)

**Comment by PicoJr** [comment]
Thanks for the data, it really helped pinpoint the issue.

I used `rtw` compiled in debug mode to obtain a backtrace:

```
...
  14: core::slice::<impl [T]>::chunks_exact
             at ./.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/macros/mod.rs:34
  15: rtw::timeline::chunkify
             at src/timeline.rs:20
...
```

I called [chunks_exact](https://doc.rust-lang.org/std/primitive.slice.html#method.chunks_exact) with `chunk_size = 0` in `src/timeline.rs`, hence the failed assertion.

I'll make sure to fix that soon =)

Additional Notes:

BTW `chunk_size = 0` happens when some activity did not last long enough to be displayed on 1 character in the timeline.

For example, if your terminal is 120 characters wide and there is 12 hours between your first and last activity of the day, then a character is 12 * 60 min / 120 = 6 min.  It means that any activity shorter than 6 min  won't be displayed at all inside the timeline.

**Comment by PicoJr** [comment]
Clicked closed by mistake sorry

**Comment by skyfaller** [comment]
This seems like an important bug to fix, any chance you could put it in a release soon? I'm using [cargo-update](https://github.com/nabijaczleweli/cargo-update) to manage my cutting edge rust package updates, and I'd rather not go bleeding edge and constantly compile everything from git.

**Comment by PicoJr** [comment]
Done, v1.3.1 is published.
