### ISSUE TITLE
can't find overlapping activities

### ISSUE THREAD

**Issue by skyfaller** [PicoJr/rtw#33]
When I run `rtw week` I get "Error: failed to create timeline: some activities are overlapping". I pulled up the summary and I'm looking as hard as I can, and I cannot find which activities are overlapping.

- [ ] Can we implement a way to find the overlapping activities, if we're going to refuse to display timelines with overlapping activities?
- [ ] Are there actually overlapping activities in the attached .rtwh.json?

[rtwh.json.tar.gz](https://github.com/PicoJr/rtw/files/4798488/rtwh.json.tar.gz)

**Comment by PicoJr** [comment]
Hello, I'm a little busy at the moment, I'll get back to you when I know what's wrong and how to fix it =)

**Comment by PicoJr** [comment]
> Can we implement a way to find the overlapping activities, if we're going to refuse to display timelines with overlapping activities?

Yes

> Are there actually overlapping activities in the attached .rtwh.json?

No, the culprit is this piece of code:

https://github.com/PicoJr/rtw/blob/411a274469edc230850edffae3060a3b34b5ecdf/src/timeline.rs#L58-L66

This piece of code relies on the assumption that activities do not span over several days...

I'll make sure to:
- [ ] fix that when I have some time
- [ ] add a test to check the timeline is robust to that.
- [ ] display overlapping activities instead of letting people guess...

Sorry for the inconvenience. You can use the `dump` feature to visualize your week timeline on an iCalendar-compatible app while I work on a fix ;-).

**Comment by PicoJr** [comment]
fixed in 1.4.1
