### ISSUE TITLE
versioning is messed up somehow

### ISSUE THREAD

**Issue by skyfaller** [PicoJr/rtw#39]
It seems the latest release is tagged as 1.5.0 instead of the v2.0.0-alpha, so if I run cargo install-update nothing happens and I'm still running 1.5.0 from Jun 21? Something confusing is going on with the versioning. Look at https://github.com/PicoJr/rtw/releases and look at https://github.com/PicoJr/rtw/blob/dev/CHANGELOG.md and they seem to be out of sync somehow.

**Comment by PicoJr** [comment]
Hello, I publish releases on GitHub manually, it is the reason why it's sometimes out of sync ^^'

I have now published the `2.0.0-alpha` release.

`cargo install rtw` installs `1.5.0` because `2.0.0-alpha` is a pre-release, I don't know if `cargo install` can install pre-release versions, I had no success so far ^^'

I'll ask the rust community about that.

**Comment by PicoJr** [comment]
`cargo install --version 2.0.0-alpha rtw` works =)

**Comment by skyfaller** [comment]
OK, I'm running the alpha now, we'll see what happens :)
